defaults:
  - _self_
  - method: var
  - data_preprocess: example_data
  - override hydra/launcher: submitit_slurm

label_path: "../../datasets/confounder_3/east.p"
data_path: "../../product/rivers_ts_east_germany.csv"
save_path: "results/"
save_full_out: True
restrict_to: -1
map_to_summary_graph: "max"
remove_diagonal: True
dt_preprocess: True

hydra:
  launcher: 
    cpus_per_task: 4
    gpus_per_task: 0
    timeout_min: 6969
    mem_gb: 16
    exclude: ker
    #partition: workstation,robolab

  #mode: MULTIRUN
#   sweeper:
#     params:
#         method: choice("corr", "mean", "combo", "var")
