defaults:
  - _self_
  - override hydra/launcher: submitit_slurm


label_path: "../../datasets/random_5/east.p"
data_path: "../../product/rivers_ts_east_germany.csv"
# preprocess

data_preprocess:
  resolution: 6h
  interpolate: True
  subset_year: False
  subset_month: False
  subsample: 1
  normalize: False
  remove_trailing_nans_early: False


restrict_to: -1

seed: 666
save_finetune_path: "cp_finetuned_2/"
train_data_path: "../product/rivers_ts_bavaria.csv"
test_path: "../product/rivers_ts_east_germany.csv"
pretrained_path: methods/cp_models/pretrained_weights/

window_size: 600

cp_architecture: transformer
batch_size: 16


max_epochs: 500
optimizer_lr: 1e-4
weight_decay: 0.01

tensorboard:
  _target_: lightning.pytorch.loggers.tensorboard.TensorBoardLogger
  save_dir: "tensorboard"
  name: "null"
  log_graph: False
  default_hp_metric: True
  prefix: ""
  version: null


hydra:
#   mode: MULTIRUN
#   sweeper:
#     params:
#         method: choice("corr", "mean", "combo", "var")
#         resolution_value: choice("1H", "6H")

  launcher: 
    nodes: 1
    cpus_per_task: 1
    gpus_per_node: 1
    timeout_min: 60
    mem_gb: 8
    partition: gpu,gpu1  #standard
