label_path: ../../datasets/random_5/east.p
data_path: ../../product/rivers_ts_east_germany.csv
data_preprocess:
  resolution: 6h
  interpolate: true
  subset_year: false
  subset_month: false
  subsample: 1
  normalize: true
  remove_trailing_nans_early: false
restrict_to: -1
seed: 4242
save_finetune_path: cp_finetuned_2/
train_data_path: ../product/rivers_ts_bavaria.csv
test_path: ../product/rivers_ts_east_germany.csv
pretrained_path: methods/cp_models/pretrained_weights/
window_size: 600
cp_architecture: unidirectional
batch_size: 128
max_epochs: 20
optimizer_lr: 0.001
weight_decay: 0.02
tensorboard:
  _target_: lightning.pytorch.loggers.tensorboard.TensorBoardLogger
  save_dir: tensorboard
  name: 'null'
  log_graph: false
  default_hp_metric: true
  prefix: ''
  version: null
