name: stic
max_lag: 5
batch_size: 256
lr: 0.01
# my addition because my tests resulted in increased lr in the beginning.
# so now we start with the high lr above and decrease every STIC_lr_decay_stepsize
# epochs the lr by dividing with 10.
# disable this behavior with STIC_lr_decay_stepsize = STIC_epochs +1
lr_decay_stepsize: 200 
epochs: 1000
tqdm_bar: true